import React, { useEffect, useState } from 'react'
import { ArrowRight, LogOut, MapPin, PackageCheck, Phone, UserRound } from 'lucide-react'
import { Link, Navigate, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext.jsx'
import { getOrders, updateProfile } from '../services/api.js'

const money = value => `Rs. ${Number(value).toLocaleString('en-LK')}`

export default function CustomerDashboard() {
  const { session, loading, logout, refresh } = useAuth(); const navigate = useNavigate()
  const [orders, setOrders] = useState([]); const [form, setForm] = useState({ name: '', phone: '', address: '' }); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const customer = session?.customer
  useEffect(() => { if (!customer) return; setForm({ name: customer.name, phone: customer.phone || '', address: customer.address || '' }); getOrders().then(setOrders).catch(() => setError('Your order history could not be loaded right now.')) }, [customer?.id])
  if (loading) return <div className="page-shell inner-page auth-loading">Opening your account…</div>
  if (!session) return <Navigate to="/login" replace state={{ from: '/dashboard' }} />
  if (session.role !== 'customer') return <Navigate to="/admin" replace />
  async function save(event) { event.preventDefault(); setBusy(true); setNotice(''); setError(''); try { await updateProfile(form); await refresh(); setNotice('Your delivery details have been saved.') } catch (err) { setError(err.response?.data?.detail || 'Could not save your account details.') } finally { setBusy(false) } }
  async function signOut() { try { await logout() } finally { navigate('/login', { replace: true }) } }
  return <div className="page-shell inner-page account-dashboard"><div className="dashboard-heading"><div><span className="eyebrow"><i /> Your Rushi account</span><h1>Welcome, <em>{customer?.name?.split(' ')[0]}.</em></h1><p>Your table, your orders, all in one place.</p></div><button className="text-link dashboard-signout" onClick={signOut}><LogOut size={16} /> Sign out</button></div><div className="dashboard-grid"><section className="account-card order-history-card"><div className="account-card-heading"><div><span className="eyebrow">From our table to yours</span><h2>Your orders</h2></div><PackageCheck /></div>{orders.length ? <div className="customer-order-list">{orders.map(order => <article className="customer-order" key={order.id}><div className="customer-order-top"><strong>{order.order_number}</strong><span className={`status-pill status-${order.status}`}>{order.status.replaceAll('_', ' ')}</span></div><div className="customer-order-lines">{order.items.map(item => <span key={item.id}>{item.food_name} × {item.quantity}</span>)}</div><div className="customer-order-foot"><span>{new Date(order.created_at).toLocaleDateString('en-LK', { dateStyle: 'medium' })}</span><strong>{money(order.total_amount)}</strong></div></article>)}</div> : <div className="account-empty"><PackageCheck size={24} /><p>Your first meal is waiting to be shared.</p><Link className="text-link" to="/menu">Explore our menu <ArrowRight size={15} /></Link></div>}</section><section className="account-card profile-card"><div className="account-card-heading"><div><span className="eyebrow">The details</span><h2>Your profile</h2></div><UserRound /></div><p className="profile-email">{customer?.email}</p><form className="account-form" onSubmit={save}><label className="form-field"><span>Your name</span><div><UserRound size={16} /><input required minLength="2" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></div></label><label className="form-field"><span>Phone number</span><div><Phone size={16} /><input required minLength="5" autoComplete="tel" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} placeholder="+94 77 123 4567" /></div></label><label className="form-field"><span>Delivery address</span><div className="textarea-wrap"><MapPin size={16} /><textarea rows="3" required minLength="5" autoComplete="street-address" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} placeholder="Street, neighbourhood, Jaffna" /></div></label>{error && <p className="form-error" role="alert">{error}</p>}{notice && <p className="form-success" role="status">{notice}</p>}<button className="button button-full" disabled={busy}>{busy ? 'Saving…' : 'Save my details'} <ArrowRight size={16} /></button></form></section></div></div>
}
